# Generated by Django 4.1 on 2023-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0091_action_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="annonymous",
            field=models.BooleanField(default=False),
        ),
    ]
