# Generated by Django 4.1 on 2023-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0015_merge_20230411_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encryption_key", models.CharField(max_length=44)),
            ],
        ),
    ]
