# Generated by Django 4.1 on 2023-07-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0016_rhcommentthreadmodel_anchor"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
